name: Update version no.
on:
  push:
    paths: ["DESCRIPTION"]
permissions:
  contents: write
jobs:
  update-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Update
        run: |
          Rscript -e 'cat(paste0(".onAttach <- function(libname, pkgname) {\n    packageStartupMessage(\"lhm version ", scan("DESCRIPTION",what=character(),skip=3,nlines=1,quiet=TRUE)[2], " (", format(Sys.Date(), format = "%d-%b-%Y"), ")\")\n}\n"), file = "R/zzz.R")'
          Rscript -e 'DESC <- readLines("DESCRIPTION"); DESC[5] <- paste("Date:", Sys.Date()); writeLines(DESC, con = "DESCRIPTION")'
        
      - name: Commit update
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add R/zzz.R DESCRIPTION
          git commit -m "Update version number" || echo "No changes to commit"
          git push
